# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_POINTING=y

# Anti-idle (mouse jiggler)
CONFIG_ZMK_ANTI_IDLE=y
CONFIG_ZMK_ANTI_IDLE_ENABLE_ONLY_CONNECTED=n
CONFIG_ZMK_ANTI_IDLE_SHARED_ENDPOINT_CONFIGURATION=y
